"""updated user model

Revision ID: 385740669c3f
Revises: a1e46efe45f0
Create Date: 2026-06-23 11:46:07.180549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385740669c3f'
down_revision: Union[str, Sequence[str], None] = 'a1e46efe45f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_bank_emp_id'), 'users', ['bank_emp_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_bank_emp_id'), table_name='users')
    # ### end Alembic commands ###
