"""add pdf fields

Revision ID: a3e7c154ba2c
Revises: 385740669c3f
Create Date: 2026-06-24 11:47:00.222375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e7c154ba2c'
down_revision: Union[str, Sequence[str], None] = '385740669c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('pdf_path', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'approved_at')
    op.drop_column('meetings', 'pdf_path')
    # ### end Alembic commands ###
