"""add speaker_mapping_mode

Revision ID: b6c157d0b96e
Revises: ba3ab58d4d5d
Create Date: 2026-06-25 13:15:19.704035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c157d0b96e'
down_revision: Union[str, Sequence[str], None] = 'ba3ab58d4d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('speaker_mapping_mode', sa.String(), server_default='manual', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'speaker_mapping_mode')
    # ### end Alembic commands ###
