"""add created_by_user_id

Revision ID: ba3ab58d4d5d
Revises: a3e7c154ba2c
Create Date: 2026-06-24 12:38:31.779720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3ab58d4d5d'
down_revision: Union[str, Sequence[str], None] = 'a3e7c154ba2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'meetings', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'created_by_user_id')
    # ### end Alembic commands ###
